let level1; 

/**
 * Initializes the level with predefined objects.
 * @function
 */
function initLevel() { level1 = new Level(
[
    new Chicken(),
    new Chicken(),
    new Chicken(),
    new Chicken(),
    new Chicken(),
    new Chicken(),
    new Chicken(),
    new Chicken(),
    new BabyChicken(),
    new BabyChicken(),
    new BabyChicken(),
    new BabyChicken(),
    new BabyChicken(),
    new BabyChicken(),
    new BabyChicken(),
    new BabyChicken(),
    new BabyChicken(),
],
[
    new Endboss()
],
[
    new Cloud(),
    new Cloud(),
    new Cloud(),
    new Cloud(),
    new Cloud(),
    new Cloud(),
    new Cloud(),
    new Cloud(),
    new Cloud(),
    new Cloud(),
    new Cloud(),
    new Cloud(),
], 
[   
    new Heart(),
    new Heart(),
    new Heart(),
    new Heart(),
    new Heart(),
    new Heart(),
    new Heart(),
    new Heart(),
    new Heart(),
    new Heart(),
    new Heart()
], 
[   
    new Bottle(),
    new Bottle(),
    new Bottle(),
    new Bottle(),
    new Bottle(),
    new Bottle(),
    new Bottle(),
    new Bottle(),
    new Bottle(),
    new Bottle(),
    new Bottle(),
    new Bottle(),
    new Bottle(),
    new Bottle(),
    new Bottle(),
    new Bottle(),
    new Bottle(),
    new Bottle(),
    new Bottle()
],
[
    new Coins(),
    new Coins(),
    new Coins(),
    new Coins(),
    new Coins(),
    new Coins(),
    new Coins(),
    new Coins(),
    new Coins(),
    new Coins(),
    new Coins(),
    new Coins(),
    new Coins(),
    new Coins(),
],
[
    new BackgroundObject('../El_Pollo_Loco/img_pollo_locco/img/5_background/layers/air.png', -719),
    new BackgroundObject('../El_Pollo_Loco/img_pollo_locco/img/5_background/layers/3_third_layer/2.png', -719),
    new BackgroundObject('../El_Pollo_Loco/img_pollo_locco/img/5_background/layers/2_second_layer/2.png', -719),
    new BackgroundObject('../El_Pollo_Loco/img_pollo_locco/img/5_background/layers/1_first_layer/2.png', -719),

    new BackgroundObject('../El_Pollo_Loco/img_pollo_locco/img/5_background/layers/air.png', 0),
    new BackgroundObject('../El_Pollo_Loco/img_pollo_locco/img/5_background/layers/3_third_layer/1.png', 0),
    new BackgroundObject('../El_Pollo_Loco/img_pollo_locco/img/5_background/layers/2_second_layer/1.png', 0),
    new BackgroundObject('../El_Pollo_Loco/img_pollo_locco/img/5_background/layers/1_first_layer/1.png', 0),
    new BackgroundObject('../El_Pollo_Loco/img_pollo_locco/img/5_background/layers/air.png', 719),
    new BackgroundObject('../El_Pollo_Loco/img_pollo_locco/img/5_background/layers/3_third_layer/2.png', 719),
    new BackgroundObject('../El_Pollo_Loco/img_pollo_locco/img/5_background/layers/2_second_layer/2.png', 719),
    new BackgroundObject('../El_Pollo_Loco/img_pollo_locco/img/5_background/layers/1_first_layer/2.png', 719),

    new BackgroundObject('../El_Pollo_Loco/img_pollo_locco/img/5_background/layers/air.png', 719 * 2),
    new BackgroundObject('../El_Pollo_Loco/img_pollo_locco/img/5_background/layers/3_third_layer/1.png', 719 * 2),
    new BackgroundObject('../El_Pollo_Loco/img_pollo_locco/img/5_background/layers/2_second_layer/1.png', 719 * 2),
    new BackgroundObject('../El_Pollo_Loco/img_pollo_locco/img/5_background/layers/1_first_layer/1.png', 719 * 2),
    new BackgroundObject('../El_Pollo_Loco/img_pollo_locco/img/5_background/layers/air.png', 719 * 3),
    new BackgroundObject('../El_Pollo_Loco/img_pollo_locco/img/5_background/layers/3_third_layer/2.png', 719 * 3),
    new BackgroundObject('../El_Pollo_Loco/img_pollo_locco/img/5_background/layers/2_second_layer/2.png', 719 * 3),
    new BackgroundObject('../El_Pollo_Loco/img_pollo_locco/img/5_background/layers/1_first_layer/2.png', 719 * 3),

    new BackgroundObject('../El_Pollo_Loco/img_pollo_locco/img/5_background/layers/air.png', 719 * 4),
    new BackgroundObject('../El_Pollo_Loco/img_pollo_locco/img/5_background/layers/3_third_layer/1.png', 719 * 4),
    new BackgroundObject('../El_Pollo_Loco/img_pollo_locco/img/5_background/layers/2_second_layer/1.png', 719 * 4),
    new BackgroundObject('../El_Pollo_Loco/img_pollo_locco/img/5_background/layers/1_first_layer/1.png', 719 * 4),
    new BackgroundObject('../El_Pollo_Loco/img_pollo_locco/img/5_background/layers/air.png', 719 * 5),
    new BackgroundObject('../El_Pollo_Loco/img_pollo_locco/img/5_background/layers/3_third_layer/2.png', 719 * 5),
    new BackgroundObject('../El_Pollo_Loco/img_pollo_locco/img/5_background/layers/2_second_layer/2.png', 719 * 5),
    new BackgroundObject('../El_Pollo_Loco/img_pollo_locco/img/5_background/layers/1_first_layer/2.png', 719 * 5),

    new BackgroundObject('../El_Pollo_Loco/img_pollo_locco/img/5_background/layers/air.png', 719 * 6),
    new BackgroundObject('../El_Pollo_Loco/img_pollo_locco/img/5_background/layers/3_third_layer/1.png', 719 * 6),
    new BackgroundObject('../El_Pollo_Loco/img_pollo_locco/img/5_background/layers/2_second_layer/1.png', 719 * 6),
    new BackgroundObject('../El_Pollo_Loco/img_pollo_locco/img/5_background/layers/1_first_layer/1.png', 719 * 6),
    new BackgroundObject('../El_Pollo_Loco/img_pollo_locco/img/5_background/layers/air.png', 719 * 7),
    new BackgroundObject('../El_Pollo_Loco/img_pollo_locco/img/5_background/layers/3_third_layer/2.png', 719 * 7),
    new BackgroundObject('../El_Pollo_Loco/img_pollo_locco/img/5_background/layers/2_second_layer/2.png', 719 * 7),
    new BackgroundObject('../El_Pollo_Loco/img_pollo_locco/img/5_background/layers/1_first_layer/2.png', 719 * 7),

    new BackgroundObject('../El_Pollo_Loco/img_pollo_locco/img/5_background/layers/air.png', 719 * 8),
    new BackgroundObject('../El_Pollo_Loco/img_pollo_locco/img/5_background/layers/3_third_layer/1.png', 719 * 8),
    new BackgroundObject('../El_Pollo_Loco/img_pollo_locco/img/5_background/layers/2_second_layer/1.png', 719 * 8),
    new BackgroundObject('../El_Pollo_Loco/img_pollo_locco/img/5_background/layers/1_first_layer/1.png', 719 * 8),
    new BackgroundObject('../El_Pollo_Loco/img_pollo_locco/img/5_background/layers/air.png', 719 * 9),
    new BackgroundObject('../El_Pollo_Loco/img_pollo_locco/img/5_background/layers/3_third_layer/2.png', 719 * 9),
    new BackgroundObject('../El_Pollo_Loco/img_pollo_locco/img/5_background/layers/2_second_layer/2.png', 719 * 9),
    new BackgroundObject('../El_Pollo_Loco/img_pollo_locco/img/5_background/layers/1_first_layer/2.png', 719 * 9),

    new BackgroundObject('../El_Pollo_Loco/img_pollo_locco/img/5_background/layers/air.png', 719 * 10),
    new BackgroundObject('../El_Pollo_Loco/img_pollo_locco/img/5_background/layers/3_third_layer/1.png', 719 * 10),
    new BackgroundObject('../El_Pollo_Loco/img_pollo_locco/img/5_background/layers/2_second_layer/1.png', 719 * 10),
    new BackgroundObject('../El_Pollo_Loco/img_pollo_locco/img/5_background/layers/1_first_layer/1.png', 719 * 10),
    new BackgroundObject('../El_Pollo_Loco/img_pollo_locco/img/5_background/layers/air.png', 719 * 11),
    new BackgroundObject('../El_Pollo_Loco/img_pollo_locco/img/5_background/layers/3_third_layer/2.png', 719 * 11),
    new BackgroundObject('../El_Pollo_Loco/img_pollo_locco/img/5_background/layers/2_second_layer/2.png', 719 * 11),
    new BackgroundObject('../El_Pollo_Loco/img_pollo_locco/img/5_background/layers/1_first_layer/2.png', 719 * 11)
    ]
)};
